version: "3.0"

services:
  app:
    image: jregner/nginx:1.19
    env_file:
      - .env
    volumes:
      - './src:/var/www/html'
    depends_on:
      - php
      - mysql
    networks:
      - app
    labels:
      - 'traefik.http.routers.api.rule=Host(`${DOMAIN}`)'
      - 'traefik.docker.network=docker-tools_traefik'

  php:
    image: jregner/php:8.0-fpm-dev
    user: "${USER}:${GROUP}"
    volumes:
      - './src:/var/www/html'
    networks:
      - app

  mysql:
    image: mysql:8.0
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DATABASE: '${DB_DATABASE}'
      MYSQL_USER: '${DB_USERNAME}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - 'mysqlvolume:/var/lib/mysql'
    networks:
      - app

volumes:
  mysqlvolume:
    driver: local

networks:
  traefik:
    external:
      name: docker-tools_traefik
  app:
    driver: bridge
